# Generated by Django 5.2.12 on 2026-04-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.TextField(blank=True, null=True)),
                ('adress', models.TextField(blank=True, null=True)),
                ('smart', models.TextField(blank=True, null=True)),
                ('rec', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dogovor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListKontrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gru', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('napra', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('fio_ruk', models.TextField(blank=True, null=True)),
                ('prohod_pract', models.TextField(blank=True, null=True)),
                ('org', models.TextField(blank=True, null=True)),
                ('ryk_p', models.TextField(blank=True, null=True)),
                ('fioprisut', models.TextField(blank=True, null=True)),
                ('fio_ots', models.TextField(blank=True, null=True)),
                ('prichina', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'list_kontrol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prilojenie12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modul', models.TextField(blank=True, null=True)),
                ('start', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('final', models.FloatField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('nara', models.TextField(blank=True, null=True)),
                ('akd', models.IntegerField(blank=True, null=True)),
                ('fio_stud', models.TextField(blank=True, null=True)),
                ('date_birth', models.TextField(blank=True, null=True)),
                ('fioruk', models.TextField(blank=True, db_column='fioRuk', null=True)),
                ('num_ruk', models.IntegerField(blank=True, null=True)),
                ('fioprofruk', models.TextField(blank=True, db_column='fioProfRuk', null=True)),
                ('doljnost_profruk', models.TextField(blank=True, db_column='doljnost_profRuk', null=True)),
                ('numprofruk', models.TextField(blank=True, db_column='numProfRuk', null=True)),
                ('org', models.TextField(blank=True, null=True)),
                ('fiootv', models.TextField(blank=True, db_column='fioOtv', null=True)),
                ('doljotv', models.TextField(blank=True, db_column='doljOtv', null=True)),
                ('numberotv', models.TextField(blank=True, db_column='numberOtv', null=True)),
                ('addres', models.TextField(blank=True, null=True)),
                ('namepomech', models.TextField(blank=True, db_column='namePomech', null=True)),
            ],
            options={
                'db_table': 'prilojenie12',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otchestvo', models.TextField(blank=True, null=True)),
                ('familia', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('otchestvo', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('checkan', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
