# Generated by Django 5.2.12 on 2026-04-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainNYV', '0002_alter_userprofile_table_documenttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
