# Generated by Django 5.2.12 on 2026-04-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainNYV', '0002_dogovor_listkontrol_prilojenie12_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dogovor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='listkontrol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prilojenie12',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
