# Generated by Django 5.2.12 on 2026-04-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainNYV', '0003_alter_document_options_alter_dogovor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dogovor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='listkontrol',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prilojenie12',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
