# Generated by Django 5.2.12 on 2026-04-17 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainNYV', '0003_alter_documenttemplate_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={},
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='doc_type',
            field=models.CharField(choices=[('contract', 'Договор'), ('appendix', 'Приложение'), ('control', 'Лист контроля')], default='contract', max_length=20),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_file',
            field=models.FileField(upload_to='templates/documents/'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
