# Generated by Django 5.2.12 on 2026-04-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainNYV', '0004_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='document',
        ),
    ]
