# Generated by Django 5.2.12 on 2026-04-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainNYV', '0005_alter_document_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listkontrol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prilojenie12',
            options={},
        ),
    ]
