# Generated by Django 5.2.12 on 2026-04-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainNYV', '0006_alter_listkontrol_options_alter_prilojenie12_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listkontrol',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prilojenie12',
            options={'managed': False},
        ),
    ]
