# Generated by Django 5.2.13 on 2026-05-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainNYV', '0004_alter_document_options_alter_dogovor_options_and_more'),
        ('mainNYV', '0007_alter_listkontrol_options_alter_prilojenie12_options'),
    ]

    operations = [
    ]
