# Generated by Django 5.2.13 on 2026-05-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainNYV', '0008_merge_20260505_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Naprav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_naprav', models.CharField(blank=True, null=True)),
                ('kod', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'naprav',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
