# Generated by Django 5.2.13 on 2026-05-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainNYV', '0009_modules_naprav_delete_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
